action_id: trunk-cache-prune
date: 2023-11-06 13:53:52
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\r\n"
  err: ""
timestamp: 1699278832
full_timestamp:
  nanos: 482218000
  seconds: 1699278832
trunk_version: 1.17.1
