@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\user\AppData\Local\trunk\tools\osv-scanner\1.4.3-a912ca692a2d8a9070d8abc452c79d0b;C:\Users\user\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\user\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
