@echo off
REM Generated by trunk tool 'svgo'
set PATH=C:\Users\user\AppData\Local\trunk\tools\svgo\3.0.2-d2212dad4b143ad90f138bf0ce231eaa/node_modules/.bin;C:\Users\user\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4/bin;C:\Users\user\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4;C:\Users\user\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\user\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set NODE_PATH=C:\Users\user\AppData\Local\trunk\tools\svgo\3.0.2-d2212dad4b143ad90f138bf0ce231eaa/node_modules

start /w /b svgo %*
